version: '1'

services:
  db:
    image: postgres:14beta2-alpine3.14
    restart: always
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: authserver
    ports:
      - "3030:3030"